import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import prisma from "@/lib/prisma";
import { Users, BarChart3, ArrowRight, MessageSquare } from "lucide-react";
import Link from "next/link";

export default async function AdminOverviewPage() {
  const session = await getServerSession(authOptions);

  const [totalUsers, totalResumes, feedbacks] = await Promise.all([
    prisma.user.count(),
    prisma.resume.count(),
    prisma.feedback.findMany({
      orderBy: { createdAt: "desc" },
      take: 10,
      include: { user: { select: { name: true, email: true } } },
    }),
  ]);

  const recentUsers = await prisma.user.findMany({
    orderBy: { createdAt: "desc" },
    take: 5,
    select: { id: true, name: true, email: true, createdAt: true },
  });

  const stats = [
    { label: "Total Users", value: totalUsers, icon: Users, color: "text-violet-400", bg: "bg-violet-500/10 border-violet-500/15" },
    { label: "Total Resumes", value: totalResumes, icon: BarChart3, color: "text-cyan-400", bg: "bg-cyan-500/10 border-cyan-500/15" },
    { label: "Feedbacks", value: feedbacks.length, icon: MessageSquare, color: "text-amber-400", bg: "bg-amber-500/10 border-amber-500/15" },
  ];

  return (
    <div className="p-8 max-w-7xl mx-auto space-y-8">
      <div>
        <h1 className="text-3xl font-extrabold font-heading tracking-tight">Admin Overview</h1>
        <p className="text-muted-foreground mt-1">
          Welcome back, {session?.user?.name?.split(" ")[0] || 'Admin'}. Here's what's happening.
        </p>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-5">
        {stats.map(({ label, value, icon: Icon, color, bg }) => (
          <div key={label} className={`glass-card rounded-2xl p-5 border ${bg} flex items-center gap-4`}>
            <div className={`w-12 h-12 rounded-xl flex items-center justify-center ${bg}`}>
              <Icon size={22} className={color} />
            </div>
            <div>
              <p className={`text-3xl font-extrabold font-heading ${color}`}>{value}</p>
              <p className="text-xs text-muted-foreground mt-0.5">{label}</p>
            </div>
          </div>
        ))}
      </div>

      {/* Quick Actions */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        <div className="glass-card rounded-2xl p-6 border border-violet-500/15 bg-violet-500/5 flex flex-col justify-between">
          <div>
            <div className="flex items-center gap-2 mb-4">
              <Users size={18} className="text-violet-400" />
              <h3 className="font-bold font-heading">Manage Users</h3>
            </div>
            <p className="text-sm text-muted-foreground mb-4">
              View all registered users and manage their access to the platform.
            </p>
          </div>
          <Link
            href="/admin/users"
            className="inline-flex items-center gap-2 text-sm font-semibold text-violet-400 hover:text-violet-300 transition-colors mt-auto"
          >
            Go to Users <ArrowRight size={14} />
          </Link>
        </div>

        <div className="glass-card rounded-2xl p-6 border border-cyan-500/15 bg-cyan-500/5 flex flex-col justify-between">
          <div>
            <div className="flex items-center gap-2 mb-4">
              <BarChart3 size={18} className="text-cyan-400" />
              <h3 className="font-bold font-heading">Manage Resumes</h3>
            </div>
            <p className="text-sm text-muted-foreground mb-4">
              View all optimized resumes generated by users.
            </p>
          </div>
          <Link
            href="/admin/resumes"
            className="inline-flex items-center gap-2 text-sm font-semibold text-cyan-400 hover:text-cyan-300 transition-colors mt-auto"
          >
            Go to Resumes <ArrowRight size={14} />
          </Link>
        </div>
      </div>

      {/* User Feedbacks */}
      <div className="glass-card rounded-2xl border border-border/30 overflow-hidden">
        <div className="p-6 border-b border-border/30 flex items-center justify-between">
          <h3 className="font-bold font-heading flex items-center gap-2">
            <MessageSquare size={18} className="text-amber-400" /> User Feedbacks
          </h3>
        </div>
        <div className="p-6 space-y-4">
          {feedbacks.length === 0 ? (
            <p className="text-muted-foreground text-sm text-center">No feedbacks yet.</p>
          ) : (
            feedbacks.map(f => (
              <div key={f.id} className="p-4 rounded-xl bg-muted/20 border border-border/30 flex flex-col gap-2">
                <div className="flex items-center justify-between flex-wrap gap-2">
                  <div className="flex items-center gap-2">
                    <div className="w-8 h-8 rounded-full bg-primary/10 border border-primary/20 flex items-center justify-center text-xs font-bold text-primary shrink-0">
                      {f.user.name.split(" ").map((n: string) => n[0]).slice(0, 2).join("").toUpperCase()}
                    </div>
                    <div>
                      <p className="text-sm font-bold">{f.user.name}</p>
                      <p className="text-xs text-muted-foreground">{f.user.email}</p>
                    </div>
                  </div>
                  <span className="text-xs text-muted-foreground">
                    {new Date(f.createdAt).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
                  </span>
                </div>
                <p className="text-sm text-foreground/90 bg-muted/40 p-3 rounded-lg border border-border/50">
                  {f.message}
                </p>
              </div>
            ))
          )}
        </div>
      </div>

      {/* Recent Users */}
      <div className="glass-card rounded-2xl border border-border/30 overflow-hidden">
        <div className="p-6 border-b border-border/30 flex items-center justify-between">
          <h3 className="font-bold font-heading">Recent Signups</h3>
          <Link href="/admin/users" className="text-xs text-primary hover:text-primary/80 transition-colors">
            View all →
          </Link>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm data-table">
            <thead>
              <tr>
                {["Name", "Email", "Joined"].map(h => (
                  <th key={h} className="px-6 py-3 text-xs font-semibold text-muted-foreground text-left">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {recentUsers.map(u => (
                <tr key={u.id} className="border-t border-border/20">
                  <td className="px-6 py-4 font-medium">{u.name}</td>
                  <td className="px-6 py-4 text-muted-foreground">{u.email}</td>
                  <td className="px-6 py-4 text-muted-foreground">
                    {new Date(u.createdAt).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
                  </td>
                </tr>
              ))}
              {recentUsers.length === 0 && (
                <tr><td colSpan={3} className="px-6 py-8 text-center text-muted-foreground text-sm">No users found</td></tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
